package RemoteInterface;


/**
* RemoteInterface/remoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/remote.idl
* Friday, August 2, 2019 3:19:13 PM EDT
*/

public interface remoteOperations 
{
  String viewEvents (String eventType);
  String viewEvents2 (String eventType);
  void registerEmployee (String userId);
  String checkUser (String userId);
  String addEvent (String eventype, String eventid, int bookingcapacity);
  String deleteEvent (String eventype, String eventid);
  String bookEvents (String CustomerId, String eventtype, String eventId);
  String viewBookedEvents (String CustomerId);
  String viewBookedEvents2 (String CustomerId);
  String cancelEvents (String CustomerId, String eventtype, String eventId);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface remoteOperations
