package ClientServerInterfaceApp;


/**
* ClientServerInterfaceApp/ClientServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/Message.idl
* Friday, August 2, 2019 12:26:17 PM EDT
*/

public interface ClientServerInterface extends ClientServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientServerInterface
