package ClientServerInterfaceApp;

/**
* ClientServerInterfaceApp/ClientServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/Message.idl
* Friday, August 2, 2019 12:26:17 PM EDT
*/

public final class ClientServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientServerInterfaceApp.ClientServerInterface value = null;

  public ClientServerInterfaceHolder ()
  {
  }

  public ClientServerInterfaceHolder (ClientServerInterfaceApp.ClientServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientServerInterfaceApp.ClientServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientServerInterfaceApp.ClientServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientServerInterfaceApp.ClientServerInterfaceHelper.type ();
  }

}
