package ClientServerInterfaceApp;


/**
* ClientServerInterfaceApp/ClientServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/Message.idl
* Friday, August 2, 2019 12:26:17 PM EDT
*/

public interface ClientServerInterfaceOperations 
{
  String addEvent (String eventType, String eventId, int bookingCapacity);
  String deleteEvent (String eventType, String eventId);
  String listEventAvailability (String eventType);
  String bookEvent (String customerId, String eventType, String eventId);
  String getBookingSchedule (String customerId);
  String cancelEvents (String cutomerId, String eventType, String eventId);
  String swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);
  void printHashMap ();
} // interface ClientServerInterfaceOperations
