package FrontEndApp;


/**
* FrontEndApp/FrontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/FrontEndApp.idl
* Sunday, August 4, 2019 8:58:30 PM EDT
*/

public interface FrontEndInterface extends FrontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndInterface
