package FrontEndApp;


/**
* FrontEndApp/FrontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/FrontEndApp.idl
* Sunday, August 4, 2019 8:58:31 PM EDT
*/

public interface FrontEndInterfaceOperations 
{
  String addEvent (String userID, String eventType, String eventId, int bookingCapacity);
  String deleteEvent (String userID, String eventType, String eventId);
  String listEventAvailability (String userID, String eventType);
  String bookEvent (String customerId, String eventType, String eventId);
  String getBookingSchedule (String customerId);
  String cancelEvents (String cutomerId, String eventType, String eventId);
  String swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);
} // interface FrontEndInterfaceOperations
