package FrontEndApp;


/**
* FrontEndApp/FrontEndInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/ASG2/src/FrontEndApp.idl
* Sunday, August 4, 2019 8:58:30 PM EDT
*/

abstract public class FrontEndInterfaceHelper
{
  private static String  _id = "IDL:FrontEndApp/FrontEndInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEndApp.FrontEndInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEndApp.FrontEndInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FrontEndApp.FrontEndInterfaceHelper.id (), "FrontEndInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEndApp.FrontEndInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FrontEndInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEndApp.FrontEndInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FrontEndApp.FrontEndInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEndApp.FrontEndInterface)
      return (FrontEndApp.FrontEndInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEndApp._FrontEndInterfaceStub stub = new FrontEndApp._FrontEndInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FrontEndApp.FrontEndInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEndApp.FrontEndInterface)
      return (FrontEndApp.FrontEndInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEndApp._FrontEndInterfaceStub stub = new FrontEndApp._FrontEndInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
